"""init

Revision ID: 1984237ef78f
Revises: 25fb2b145533
Create Date: 2022-10-24 21:57:04.588971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1984237ef78f'
down_revision = '25fb2b145533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
