"""init

Revision ID: 25fb2b145533
Revises: 1c373ba03045
Create Date: 2022-10-24 21:51:33.498428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fb2b145533'
down_revision = '1c373ba03045'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
